### ISSUE TITLE
Error: Unrecognized network https://sdk-testnet.aepps.com

### ISSUE THREAD

**Issue by dadaphl** [aeternity/aepp-forgae-js#133]
```
$ node -v
v10.10.0
$ forgae --version
1.3.2
$ forgae init
===== Initializing ForgAE =====
===== Installing aepp-sdk =====
===== Installing ForgAE locally =====
===== Installing yarn locally =====
===== Creating project file & dir structure =====
===== Creating contracts directory =====
===== Creating tests directory =====
===== Creating integrations directory =====
===== Creating deploy directory =====
===== Creating docker directory =====
===== ForgAE was successfully initialized! =====
$ ls -la
total 136
drwxr-xr-x   12 username  staff    408 Apr  8 23:25 .
drwxr-xr-x   14 username  staff    476 Apr  8 23:24 ..
drwxr-xr-x    3 username  staff    102 Apr  8 23:24 .forgae-store
drwxr-xr-x    3 username  staff    102 Apr  8 23:25 contracts
drwxr-xr-x    3 username  staff    102 Apr  8 23:25 deployment
drwxr-xr-x   11 username  staff    374 Apr  8 23:25 docker
-rw-r--r--    1 username  staff   1548 Feb 26 16:01 docker-compose.yml
drwxr-xr-x    3 username  staff    102 Apr  8 23:25 integrations
drwxr-xr-x  172 username  staff   5848 Apr  8 23:25 node_modules
-rw-r--r--    1 username  staff  59152 Apr  8 23:25 package-lock.json
-rw-r--r--    1 username  staff    374 Apr  8 23:25 package.json
drwxr-xr-x    3 username  staff    102 Apr  8 23:25 test
$ forgae deploy -n https://sdk-testnet.aepps.com -s XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Error: Unrecognized network https://sdk-testnet.aepps.com
    at Object.getNetwork (/Users/username/dev/fashion/backend/contract/node_modules/forgae/cli-commands/utils.js:132:11)
    at new Deployer (/Users/username/dev/fashion/backend/contract/node_modules/forgae/cli-commands/forgae-deploy/forgae-deployer.js:39:30)
    at deploy (/Users/username/dev/fashion/backend/contract/deployment/deploy.js:22:17)
    at Object.run (/Users/username/.nvm/versions/node/v10.10.0/lib/node_modules/forgae/cli-commands/forgae-deploy/deploy.js:26:9)
    at Command.program.command.description.option.option.option.action (/Users/username/.nvm/versions/node/v10.10.0/lib/node_modules/forgae/cli-commands/commands.js:78:17)
    at Command.listener (/Users/username/.nvm/versions/node/v10.10.0/lib/node_modules/forgae/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:182:13)
    at Command.EventEmitter.emit (domain.js:442:20)
    at Command.parseArgs (/Users/username/.nvm/versions/node/v10.10.0/lib/node_modules/forgae/node_modules/commander/index.js:651:12)
    at Command.parse (/Users/username/.nvm/versions/node/v10.10.0/lib/node_modules/forgae/node_modules/commander/index.js:474:21)
(node:90415) UnhandledPromiseRejectionWarning: Error: Unrecognized network https://sdk-testnet.aepps.com
    at Object.getNetwork (/Users/username/dev/fashion/backend/contract/node_modules/forgae/cli-commands/utils.js:132:11)
    at new Deployer (/Users/username/dev/fashion/backend/contract/node_modules/forgae/cli-commands/forgae-deploy/forgae-deployer.js:39:30)
    at deploy (/Users/username/dev/fashion/backend/contract/deployment/deploy.js:22:17)
    at Object.run (/Users/username/.nvm/versions/node/v10.10.0/lib/node_modules/forgae/cli-commands/forgae-deploy/deploy.js:26:9)
    at Command.program.command.description.option.option.option.action (/Users/username/.nvm/versions/node/v10.10.0/lib/node_modules/forgae/cli-commands/commands.js:78:17)
    at Command.listener (/Users/username/.nvm/versions/node/v10.10.0/lib/node_modules/forgae/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:182:13)
    at Command.EventEmitter.emit (domain.js:442:20)
    at Command.parseArgs (/Users/username/.nvm/versions/node/v10.10.0/lib/node_modules/forgae/node_modules/commander/index.js:651:12)
    at Command.parse (/Users/username/.nvm/versions/node/v10.10.0/lib/node_modules/forgae/node_modules/commander/index.js:474:21)
(node:90415) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:90415) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by maptuhec** [comment]
Hey @dadaphl, you don't need to provide the whole url to the network. ForgAE currently has predefined  3 networks, and you just need to write:
`forgae deploy -n testnet -s ******` or `forgae deploy -n mainnet -s *****`

**Comment by maptuhec** [comment]
@dadaphl did you managed to deploy your contracts? So we can change the status of the issue?
